### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by borromeotlhs**
Attempted to provide a little context for those unfamiliar with Alfresco, AMPs, WARs or the MMT.  Also called out the amps and wars by name, so that "exploding AMPs into WARs" doesn't sound like an rock-loving audiophile pun.  

Also took a stab at making the individual bintray icons point to the related portions of the AMPs, but recommend the gradle build generate custom svg files from bintray automated builds for mms-repo.amp and mms-share.amp download icons.

### CODE REVIEW

**Comment by borromeotlhs** [comment]
@HuiJun Can you take a look and tell me what you think?

**Comment by HuiJun** [comment]
I think this is a good change. I think I'd also like to add a download link to the alfresco installer at the top as well.

**Comment by borromeotlhs** [comment]
Please furnish what you’d like and I’ll edit the patch.

Thanks,
TJ

**Comment by borromeotlhs** [comment]
On second thought, please merge.

**Comment by borromeotlhs** [comment]
@ivan-gomes - side note: with this merge, I just remembered that v19 was reportedly not working?  Is that true?  If not, I think this patch should land before whatever version of mdk and mms support MD client v19.0. . .

Thanks,
TJ

**Comment by ivan-gomes** [comment]
@borromeotlhs MDK 4.0.0, which is on the develop branch but unreleased, targets MagicDraw 19.0. Development is done and we are running our tests. It will not affect MMS, but regardless I think we should merge this in at the earliest convenience.

**Comment by borromeotlhs** [comment]
Roger. I don’t have merge rights, though, and would just as soon merge to
my dev branch and test on a md v19.0 client simultaneously.

Regards,
TJ

**Comment by borromeotlhs** [comment]
Thanks

**Pull request merged**
