### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by borromeotlhs**
make sure people understand that there is no json data to 'test' with

### CODE REVIEW

**Review by HuiJun — CHANGES_REQUESTED** [review]
So this rather than fixing it? lol

**Comment by HuiJun** [comment]
Closing this non-release PR to master

**Comment by borromeotlhs** [comment]
Yeah sorry. Didn’t know of a good way to get the jsondata or bring it back
in. But saw a test script with “TBD :)” for its location, so thought we
were all in a joking mood about it.

Does the test json data exist? If it does, I’d gladly update the readme to
be accurate.

**Comment by HuiJun** [comment]
Hi TJ, I've updated it for our 3.3.0 release, so no need to update it. FYI, the JsonData was moved into runner/src/test/robotframework/JsonData

**Pull request closed without merging**
